### ISSUE TITLE
Problem: Names with Square Brackets

### ISSUE THREAD

**Issue by carriontrooper** [SpacedOutChicken/DeCiv-Redux#105]
Latest version caught this:
`DeCiv Redux: Global uniques's unique "[-20]% Strength <for units with [[Ranger] ability]> <when fighting in [Friendly Land] tiles> <vs [Promotion Nullifier] units>" contains the conditional "for units with [[Ranger] ability]". This contains the parameter [Ranger which does not fit parameter type promotion !`

It seems that promotions with square brackets inside their names are unparseable like that.

**Comment by SpacedOutChicken** [comment]
It wasn't like this before. I'll alert Yair about this and see what he can do.

**Comment by SpacedOutChicken** [comment]
I've removed the offending code from DeCiv, but the issue with square brackets has since been fixed in Unciv's code.
