### ISSUE TITLE
Comunes (CoR) giving +1 population for every city.

### ISSUE THREAD

**Issue by Gagleon** [SpacedOutChicken/DeCiv-Redux#11]
As text

**Comment by SpacedOutChicken** [comment]
The Commune is supposed to increase population by 1 in the city it's in. Is it not doing that for you?

**Comment by Gagleon** [comment]
No, it's giving me +1 pop in every city.

**Comment by SpacedOutChicken** [comment]
It looks like a bug in the base game. I've reported it to Yair.

**Comment by SpacedOutChicken** [comment]
Yair's got this fixed up. It should work just fine in the next update.
