### ISSUE TITLE
https://www.microsoft.com/en-my/windows/help-me-choose?results=15-2-2-2-0-3-1-3

### ISSUE THREAD

**Issue by j3aliey** [SpacedOutChicken/DeCiv-Redux#110]
![798051d6-8e7b-c95b-ad85-988166359c2d.png](https://github.com/SpacedOutChicken/DeCiv-Redux/assets/131412829/99fe2fe9-c7d6-4a9e-8115-77cdf86fba33)

**Comment by RealBamboolord** [comment]
Wrong place?
