### ISSUE TITLE
Religion 

### ISSUE THREAD

**Issue by SchoeniosX** [SpacedOutChicken/DeCiv-Redux#121]
Why are original religions not continued? I think Christianity and Islam etc. will continue to exist even after the apocalypse. I would also appreciate if symbols like the cross are added to Christianity in religions. All of the meaningless religions in the mod don't have much influence or can't be described as "religion".

**Comment by SpacedOutChicken** [comment]
The religions as they exist in Deciv are a reflection of what I found amusing, not what I consider to be realistic. Christianity and Islam would almost certainly persevere, but I prefer to have my virtual citizens worshiping the Divine Engine instead.
