### ISSUE TITLE
Field

### ISSUE THREAD

**Issue by SchoeniosX** [SpacedOutChicken/DeCiv-Redux#122]
The fields on the soil and wheat deposits look very defective. When building a farm, the house and plant texture is missing. What the comparison of the normal state looks like:

![Screenshot_20240505-135659_Unciv](https://github.com/SpacedOutChicken/DeCiv-Redux/assets/148587231/b8f7f152-055f-41af-9ef4-39ab12bd684e)

![Screenshot_20240505-135214_Unciv](https://github.com/SpacedOutChicken/DeCiv-Redux/assets/148587231/d5920156-2b88-473f-a3aa-7e53fa5aa29c)

**Comment by RealBamboolord** [comment]
This is a tileset problem, Deciv currently only really supports FantasyHex as a tileset. (Also when playing Deciv you should turn on resource icons, as some resources like power do not have a tilesprite)

**Comment by SpacedOutChicken** [comment]
Sorry for not responding for so long. RealBamboolord said it best: always play Deciv in FantasyHex with resource icons on.
