### ISSUE TITLE
Possible 🪲🐛

### ISSUE THREAD

**Issue by Razaryth** [SpacedOutChicken/DeCiv-Redux#124]
I was running this mod on Unciv and noticed a small bug (or at least I think it's a bug? Might be a feature, lol). My civ has a lot of coastline, but for some reason the game has only let me build one wind farm tile improvement, and my civ is quickly running out of power, plz halp

**Comment by RealBamboolord** [comment]
Wind Farms can only be built in tiles with the power resource to improve that resource. As the power resource has no tilesprite, you should turn on resource icons on the map when playing Deciv. This is therefor intentional

**Comment by SpacedOutChicken** [comment]
In the original DeCiv (and its more faithful restoration, DeCiv 1), you could build Wind farms on all coastal tiles. I changed this in DeCiv Redux to make them only buildable in Power resource tiles.
