### ISSUE TITLE
Мир и золото.

### ISSUE THREAD

**Issue by Augustaf0** [SpacedOutChicken/DeCiv-Redux#14]
Проблема с торговлей нации и принятия мирного договора между ними (не проходит команда). Сложно добывать золото, затрат оказывается больше, чем самой прибыли.

**Comment by SpacedOutChicken** [comment]
I believe that this issue was with trades not going through, which was an issue in the base game. That has been fixed.

If this is about making money in DeCiv, that is difficult by design. Money is supposed to be scarce.

**Comment by Augustaf0** [comment]
Рад, что ответили, и спасибо огромное за Вашу работу!

вт, 14 дек. 2021 г., 3:58 SpacedOutChicken ***@***.***>:
