### ISSUE TITLE
Tiles prioritization

### ISSUE THREAD

**Issue by segatrade** [SpacedOutChicken/DeCiv-Redux#16]
Thank you very much for this great mod! :) 
As Children of Rust in capital city doesn't prioritize ruins and rubbie (+1 culture, +2 production, free road, + possible improvements with worker), choose useless coast second time again (0!). Longhouse and Salvage Yard available in the city:
![image](https://user-images.githubusercontent.com/39907059/152403596-858a0534-ce6f-45a9-afa2-04e262bfc92c.png)
Also it choosed several times just empty desert and badlands, but it's anyway better than coast, but much worser than ruins.

Resources > Ruins, Rubbie (+1 production anyway, + can be improved, +bonuses from buildings) > Hills > Near fresh water > Badlands, Wastland (+ can be improved) > Coast (+bonuses only from late game buildings, and it's very weak bonuses)

**Comment by SpacedOutChicken** [comment]
I do not know why the AI is turning down the ruins. I suspect that there's an excessive pro-coast bias. I'll see if I can fix that.

**Comment by SpacedOutChicken** [comment]
I haven't seen the coast issue since removing all pro-coast biases. Is the AI still picking empty Badlands over Rubble?

**Comment by SpacedOutChicken** [comment]
Part of the issue here is that the game naturally chooses nearby tiles to expand into, which isn't something that a mod can change. Nothing more I can do for this one.
