### ISSUE TITLE
Only half the water is counted towards total

### ISSUE THREAD

**Issue by Zoogzin** [SpacedOutChicken/DeCiv-Redux#17]
Doesn't matter if it's a specialist, a tile, or a building's revenue, you don't get 1 water unless the combined total between them says 2, or 2 unless it says 4, etc. Using only this mod, tried across several playthroughs.
![Screenshot_20220203-191109_UnCiv](https://user-images.githubusercontent.com/93752076/152456067-23ebe587-aebc-41f9-96d9-8e9daa4d6cb6.jpg)
![Screenshot_20220203-191118_UnCiv](https://user-images.githubusercontent.com/93752076/152456083-62e28da0-1845-42f2-a913-94ba229b0b6a.jpg)
![Screenshot_20220203-191128_UnCiv](https://user-images.githubusercontent.com/93752076/152456092-2ecb6558-365f-4b2e-9837-394ad1f00d27.jpg)

**Comment by SpacedOutChicken** [comment]
Check your stats. DeCiv Redux has the option of converting gold (water) to science. This isn't enabled in the base game, but it is enabled in this mod, and by default, half of your water gets converted to science.

If you want more water and less science, just open the stats tab in the overview and adjust the "Convert water to science" to the left.

**Comment by Zoogzin** [comment]
Woah, I had no idea that was there! Thanks for your help, much appreciated!
