### ISSUE TITLE
Scout obsolete

### ISSUE THREAD

**Issue by segatrade** [SpacedOutChicken/DeCiv-Redux#19]
Seems it's bad that Scout become obsolete - it's mostly not military unit. It's always actual - for garrison city, explore map, defend workers and upgrading to Gunman or Rifleman if weapon available with very nice traits.
![image](https://user-images.githubusercontent.com/39907059/152585490-1990f9db-149c-44e3-9e26-bd5d1a7d712d.png)
It's better to make Scouts always available

**Comment by HaneulCheong** [comment]
Since #20 has been closed, should this be closed also or do you have other plans @SpacedOutChicken?

**Comment by SpacedOutChicken** [comment]
I do have other plans. Sorry that I haven't got around to them yet. But
there will be a Forward Observer unit, along with some other new units.

**Comment by SpacedOutChicken** [comment]
The Forward Observer has officially been added, so there's a scouting unit available for later techs.

**Comment by HaneulCheong** [comment]
Implemented with 8bea8788c7fc290a44223dde8920ef96f48f1ff5. Just for the sake of documentation, you know.
