### ISSUE TITLE
Some uniques of government buildings affect 'all' cities; Unclear whether this is intended

### ISSUE THREAD

**Issue by HaneulCheong** [SpacedOutChicken/DeCiv-Redux#23]
I don't know, `"[-10]% unhappiness from population [in all cities]"` for every single Congress built sounds pretty overpowered to me. And things look pretty much the same for Council and all unique buildings derived from those two. Children of Rust's Defense Committee has `"[+15]% Strength <for [All] units> <when fighting in [Friendly Land] tiles>"`, for example. Is this intended?

**Comment by HaneulCheong** [comment]
It seems some UBs such as Legion's Senate `"Can only be built [in capital]"`. Perhaps we should apply this to every government building?

**Comment by SpacedOutChicken** [comment]
All such buildings should be only buildable in the capital. I apologize for
getting that wrong. As soon as I have access to my home computer again,
I'll fix that, but it's going to be a few days before that happens.

**Comment by HaneulCheong** [comment]
> but it's going to be a few days before that happens

Well, about that...

**Comment by SpacedOutChicken** [comment]
Thanks for the edits!
