### ISSUE TITLE
Floodplains and map generation

### ISSUE THREAD

**Issue by 4xAsh** [SpacedOutChicken/DeCiv-Redux#25]
I've troubleshoot with a variety of world generation options. This doesn't seem to be an issue when using the default base rule-set, Gods and Kings. Still unsure whether this is deliberate or not. I'm not expecting a reply. If you read this do know that this mod feels like a new game in and of itself. Thank you.
:)
Deciv Redux 4.0.0
Unciv 3.19.13

**Comment by HaneulCheong** [comment]
You know you could've written a new comment in #21 instead of openning a new issue, right...?

**Comment by SpacedOutChicken** [comment]
You're right, I could have. My bad.

**Comment by HaneulCheong** [comment]
Umm...I was replying to @4xAsh...

**Comment by 4xAsh** [comment]
> Umm...I was replying to @4xAsh...

Sorry mate. Don't care.
