### ISSUE TITLE
Bug with the latest mod version

### ISSUE THREAD

**Issue by L0wcell** [SpacedOutChicken/DeCiv-Redux#26]
After i update the mod, units with conditionals simply disappear from the list and become unavailable
Is it just me or anyone else?
Unciv 3.19.10
Deciv Redux 4.0.0
![Screenshot_20220305_152327_com unciv app](https://user-images.githubusercontent.com/96007059/156873187-998c23e0-a4fd-4434-8a02-4bd2cbbab2dc.jpg)
![Screenshot_20220305_151939_com unciv app](https://user-images.githubusercontent.com/96007059/156873190-f82364bc-d05e-49e2-833a-72e5e0bd9216.jpg)

**Comment by HaneulCheong** [comment]
> Unciv 3.19.10

Your UnCiv is outdated. Could you try updating it to 3.19.12 or later?

**Comment by SpacedOutChicken** [comment]
This issue should disappear once you've fully updated your game.
