### ISSUE TITLE
Great Administrator Citadel Warning

### ISSUE THREAD

**Issue by HaneulCheong** [SpacedOutChicken/DeCiv-Redux#28]
**Platform**
Windows 64-bit

**Version**
3.19.14

**Describe the bug**
The game's mod error locator raises the following warning:
> Great Administrator can place improvement Citadel which has no stats, preventing unit automation!

**To Reproduce**
1. Go to [Options] - [Locate mod errors]
2. Unfold [DeCiv Redux] from the mod list
3. Confirm the warning above being raised.

**Expected behavior**
To be honest...I quite don't understand the logic behind Administrators being able to build Citadels as cultured great people. I think this ability should preferably be replaced with another ability, or at least removed.

**Additional context**
Possibly related to #15. Opening this since #15 is seemingly regarding other issues which may *or may not* be related to this problem.

**Comment by SpacedOutChicken** [comment]
My logic: in base Civ 5, artists can "culture bomb", taking over nearby territory. Right now, the only way to do that in Unciv is to build a Citadel. So, I gave the Great Administrator the ability to build a citadel. I am considering removing that ability, especially since the AI can't use it.

**Comment by HaneulCheong** [comment]
Hmm, makes sense. Unfortunately Citadel's culture bomb seems to be hardcoded. This should probably be elevated to the base game's repo...

**Comment by HaneulCheong** [comment]
1d1832f23c01e4861c20d4af13d5713de871d025 seemingly closed this for now.
