### ISSUE TITLE
Translation in the translation template missing

### ISSUE THREAD

**Issue by heipizhu4** [SpacedOutChicken/DeCiv-Redux#33]
![image](https://user-images.githubusercontent.com/100454479/157880871-6d361546-dd11-4384-96e9-0f1bf7b72de0.png)

These new nations' translations are not included in the translation template.

**Comment by HaneulCheong** [comment]
So everything's good now @heipizhu4?

**Comment by heipizhu4** [comment]
Not everything is good.
e.g.:12 buildings missing(including bomb shelter,etc.)
Check sill in process

**Comment by ArchDuque-Pancake** [comment]
There are also Nations missing and some resources

**Comment by HaneulCheong** [comment]
Confirmed some policies missing from the template also; Is there any convenient way to automate the template?

**Comment by HaneulCheong** [comment]
Confirmed New Afrika missing from the template.
