### ISSUE TITLE
sanctum and national college is broken

### ISSUE THREAD

**Issue by logicminimal** [SpacedOutChicken/DeCiv-Redux#4]
sanctum requires worked resources within the city borders, now that is fine but in order to get a national wonder you need all your cities to have atleast one of 3 resources

**Comment by SpacedOutChicken** [comment]
Good point. That seems a little unfair to the Cult of Ignis, doesn't it?

**Comment by SpacedOutChicken** [comment]
[Fixed.](https://github.com/SpacedOutChicken/DeCiv-Redux/commit/a8bbe98064aaa43c2c6f678ba4ee75824b3a92f7)
