### ISSUE TITLE
Army Depot Bug

### ISSUE THREAD

**Issue by MetallicMonk** [SpacedOutChicken/DeCiv-Redux#5]
Apparently the 'Army Depot' natural wonder is not working as intended - even though the wonder is within the player's borders, no option appears on the city screen that allows acquring the Ancient Armor. Benefits of all other wonders can be acquired from the get-go if this prerequisite is fulfiled (wonder tile within borders). Not sure if the 'Secrets of the Past' tech is needed for these types of wonders to "work" as well, but it's still not showing as an option regardless of the tech in question being researched or not.

**Comment by SpacedOutChicken** [comment]
The problem is that Ancient Armor is defined as being unique to Almaty,
which means that human players can't access it at all. I'll fix that.

**Comment by MetallicMonk** [comment]
Thank you for keeping the mod alive, you're the best! <3

**Comment by SpacedOutChicken** [comment]
Upon further inspection, it appears that all three of the wonders
associated with Almaty were poorly defined. Ive corrected all of them.
Thank you for bringing this to my attention!

**Comment by SpacedOutChicken** [comment]
Have you been able to get the Army Depot to work? You need to have researched Engineering in order for the wonder to be buildable.

**Comment by MetallicMonk** [comment]
Yup, just tested it, took me a few "rerolls" to get the correct map setup to do so, but it works - once the Army Depot is within your borders and you have Engineering researched, you get the 'Salvage Army Depot' wonder as an option to build. It's giving a free Modern Armor unit once completed (amongst a ton of other great bonuses) instead of the old Ancient Armor though, but I ain't complaining lel. Great job!
