### ISSUE TITLE
Gangboss cant automate

### ISSUE THREAD

**Issue by logicminimal** [SpacedOutChicken/DeCiv-Redux#6]
despite being able to build improvements

**Comment by logicminimal** [comment]
nvm working as intended

**Comment by SpacedOutChicken** [comment]
Glad to hear it.

**Comment by logicminimal** [comment]
@SpacedOutChicken the workers dont even build farms or moisture traps on resource tiles though despite it will be a net positive gain for the civilization, seems to be a game issue

**Comment by SpacedOutChicken** [comment]
That is an issue. We'd better notify Yair.
