### ISSUE TITLE
Surveyors (Atlas) no longer have access to the "construct improvements", nor can they complete existing improvement orders. Intentional?

### ISSUE THREAD

**Issue by Zoogzin** [SpacedOutChicken/DeCiv-Redux#77]
I noticed its not mentioning improvements in civilopedia entry for surveyor, so was it intentional?
![Screenshot_20221008-231713_Unciv](https://user-images.githubusercontent.com/93752076/194738017-bcfd4740-085d-412a-bfff-04b30a4a90b8.jpg)

**Comment by SpacedOutChicken** [comment]
Sadly, yes. It was causing issues for the AI, so I  removed it.

**Comment by Zoogzin** [comment]
A necessary sacrifice then. Though losing access to the spearman unit in place of this one now feels like a negative trait, considering how quickly barbarians get access to mounted units, and surveyors dont seem to work well offensively against mounted units.
