### ISSUE TITLE
Nukes don't work

### ISSUE THREAD

**Issue by MetallicMonk** [SpacedOutChicken/DeCiv-Redux#8]
![Screenshot_20210812-215529](https://user-images.githubusercontent.com/88341369/129261227-cd88ccc0-90b9-40d3-950d-9095d412004c.png)
Not sure if I'm missing something, but neither the Tactical Nuke nor the Nuclear Missile have an option to 'Attack' - the button is always greyed out and unavailable. I'm playing the new faction, "The Mariners", but I'm not sure if they are related to the issue in any way. Am at war with the faction I'm trying to nuke and have ample uranium to spare.

**Comment by SpacedOutChicken** [comment]
It's probably not a problem with the Mariners, but with how I labeled the
nukes. I'll look into it.
