### ISSUE TITLE
Mod errors

### ISSUE THREAD

**Issue by Alucard0Reborn** [SpacedOutChicken/DeCiv-Redux#88]
Horseman obsoletes at tech Rifling, and therefore Redomestication for its upgrade Hussar may not yet be researched!
Clan Horseman obsoletes at tech Rifling, and therefore Redomestication for its upgrade Hussar may not yet be researched!
Skirmisher obsoletes at tech Rifling, and therefore Redomestication for its upgrade Dragoon may not yet be researched!
Rubble Rider obsoletes at tech Rifling, and therefore Redomestication for its upgrade Dragoon may not yet be researched!
Conscript obsoletes at tech Combined Arms, and therefore Plastics for its upgrade NBC Conscript may not yet be researched!
Rubble Militia obsoletes at tech Combined Arms, and therefore Plastics for its upgrade NBC Conscript may not yet be researched!
Hitman obsoletes at tech Replaceable Parts, and therefore Currency for its upgrade Assassin may not yet be researched!
Dinghy obsoletes at tech Replaceable Parts, and therefore Navigation for its upgrade Patrol Boat may not yet be researched!
Trimaran obsoletes at tech Replaceable Parts, and therefore Navigation for its upgrade Patrol Boat may not yet be researched!
Bandit obsoletes at tech Engineering, and therefore Rifling for its upgrade Soldier may not yet be researched!
Irregular obsoletes at tech Combined Arms, and therefore Plastics for its upgrade NBC Marksman may not yet be researched!

**Comment by SpacedOutChicken** [comment]
DeCiv's structure for promoting units doesn't quite mesh with what Unciv expects. The good news is that none of these are actual errors in the mod.

**Comment by Alucard0Reborn** [comment]
If that is the case, should I not be using the Auto update feature as it's
probably a cause for mods breaking? And why is it a thing if all it does is
break mods?
