### ISSUE TITLE
Barbarian spawn rate?

### ISSUE THREAD

**Issue by Malvisk** [SpacedOutChicken/DeCiv-Redux#96]
How much is this mod affecting barbarian spawn rates?  I understand that it's supposed to be difficult, but at Prince difficulty level the sheer amount of barbarians at the start of the game is maddening.  Encountering a barbarian camp within a few hexs of your city, spawning an outlaw (36) at the start of the game is really rough. :)

**Comment by SpacedOutChicken** [comment]
The spawn rate for Barbarians is currently hard-coded, so I can't change that. I can change the time it takes for Barbarians to enter player tiles, but for now I'm keeping that as is because it's supposed to be difficult, after all.

**Comment by RealBamboolord** [comment]
@SpacedOutChicken The barbarian Cavalry units at the start of the game are annoying hard to kill, and they can pillage your lands almost unstoppable

**Comment by Malvisk** [comment]
@SpacedOutChicken how about the attk/def 36 outlaws be delayed before they start spawning?  Then spawning at the start of the game can be devastating to progress

**Comment by SpacedOutChicken** [comment]
> @SpacedOutChicken how about the attk/def 36 outlaws be delayed before they start spawning? Then spawning at the start of the game can be devastating to progress

@Malvisk I put in a delay in spawning the Outlaw and a few other debuffs on Barbarians. They should be easier to deal with now.
